### ISSUE TITLE
HetNet

### ISSUE THREAD

**Issue by firyaguna** [mmezzavilla/ns3-mmwave#3]
Hi,

Do you have an example of script simulating a heterogeneous network with legacy LTE in macro cells and mmwave in small cells?

If not, could you please show me how I can start to do this?

Thanks in advance, and thanks for the code.

Cheers

**Comment by mychele** [comment]
Hi, 
this feature is still a WIP and it will be released soon ;)

**Comment by firyaguna** [comment]
This is great!
