### ISSUE TITLE
Fedora 25 - building problem

### ISSUE THREAD

**Issue by DmitarC** [mmezzavilla/ns3-mmwave#4]
I downloaded ns3.26 and built it successfully. Then, I tried to import mmwave module by copying it in src folder and after these commands:

./waf configure --enable-examples
./waf build

building failes, every time at different code line.

**Example1:**
[aleksandra@localhost ns-3.26]$ ./waf configure
 [aleksandra@localhost ns-3.26]$ ./waf build
....
[1442/2010] Compiling src/mmwave/model/mmwave-net-device.cc
../src/mmwave/model/mmwave-enb-mac.cc: In member function ‘void ns3::MmWaveEnbMac::DoReportBufferStatus(ns3::LteMacSapProvider::ReportBufferStatusParameters)’:
../src/mmwave/model/mmwave-enb-mac.cc:661:40: error: ‘struct ns3::LteMacSapProvider::ReportBufferStatusParameters’ has no member named ‘txPacketSizes’; did you mean ‘txQueueSize’?
   schedParams.m_txPacketSizes = params.txPacketSizes;
                                        ^~~~~~~~~~~~~
../src/mmwave/model/mmwave-enb-mac.cc:662:41: error: ‘struct ns3::LteMacSapProvider::ReportBufferStatusParameters’ has no member named ‘txPacketDelays’
   schedParams.m_txPacketDelays = params.txPacketDelays;
                                         ^~~~~~~~~~~~~~
../src/mmwave/model/mmwave-enb-mac.cc:663:42: error: ‘struct ns3::LteMacSapProvider::ReportBufferStatusParameters’ has no member named ‘retxPacketSizes’; did you mean ‘retxQueueSize’?
   schedParams.m_retxPacketSizes = params.retxPacketSizes;
                                          ^~~~~~~~~~~~~~~
../src/mmwave/model/mmwave-enb-mac.cc:664:43: error: ‘struct ns3::LteMacSapProvider::ReportBufferStatusParameters’ has no member named ‘retxPacketDelays’; did you mean ‘retxQueueHolDelay’?
   schedParams.m_retxPacketDelays = params.retxPacketDelays;
                                           ^~~~~~~~~~~~~~~~
../src/mmwave/model/mmwave-enb-mac.cc:665:38: error: ‘struct ns3::LteMacSapProvider::ReportBufferStatusParameters’ has no member named ‘arrivalRate’
   schedParams.m_arrivalRate = params.arrivalRate;
                                      ^~~~~~~~~~~

Waf: Leaving directory `/home/aleksandra/workspace/source/ns-3.26/build'
Build failed
 -> task in 'ns3-mmwave' failed (exit status 1): 
	{task 139690920454992: cxx mmwave-enb-mac.cc -> mmwave-enb-mac.cc.1.o}
['/usr/bin/g++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-std=c++11', '-Wno-error=deprecated-declarations', '-fstrict-aliasing', '-Wstrict-aliasing', '-fPIC', '-pthread', '-pthread', '-I.', '-I..', '-I/usr/include/gtk-2.0', '-I/usr/lib64/gtk-2.0/include', '-I/usr/include/pango-1.0', '-I/usr/include/atk-1.0', '-I/usr/include/cairo', '-I/usr/include/pixman-1', '-I/usr/include/libdrm', '-I/usr/include/gdk-pixbuf-2.0', '-I/usr/include/libpng16', '-I/usr/include/harfbuzz', '-I/usr/include/glib-2.0', '-I/usr/lib64/glib-2.0/include', '-I/usr/include/freetype2', '-I/usr/include/libxml2', '-DNS3_BUILD_PROFILE_DEBUG', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_PACKET_H=1', '-DHAVE_IF_TUN_H=1', '-DHAVE_SQLITE3=1', '-DHAVE_GTK2=1', '-DHAVE_LIBXML2=1', '../src/mmwave/model/mmwave-enb-mac.cc', '-c', '-o', '/home/aleksandra/workspace/source/ns-3.26/build/src/mmwave/model/mmwave-enb-mac.cc.1.o']_

**Example 2:**

[aleksandra@localhost ns-3.26]$ ./waf configure
 [aleksandra@localhost ns-3.26]$ ./waf build
....
_[1639/2010] Compiling src/mmwave/model/mmwave-spectrum-signal-parameters.cc
../src/mmwave/model/mmwave-enb-mac.cc: In member function ‘void ns3::MmWaveEnbMac::DoReportBufferStatus(ns3::LteMacSapProvider::ReportBufferStatusParameters)’:
../src/mmwave/model/mmwave-enb-mac.cc:661:40: error: ‘struct ns3::LteMacSapProvider::ReportBufferStatusParameters’ has no member named ‘txPacketSizes’; did you mean ‘txQueueSize’?
   schedParams.m_txPacketSizes = params.txPacketSizes;
                                        ^~~~~~~~~~~~~
../src/mmwave/model/mmwave-enb-mac.cc:662:41: error: ‘struct ns3::LteMacSapProvider::ReportBufferStatusParameters’ has no member named ‘txPacketDelays’
   schedParams.m_txPacketDelays = params.txPacketDelays;
                                         ^~~~~~~~~~~~~~
../src/mmwave/model/mmwave-enb-mac.cc:663:42: error: ‘struct ns3::LteMacSapProvider::ReportBufferStatusParameters’ has no member named ‘retxPacketSizes’; did you mean ‘retxQueueSize’?
   schedParams.m_retxPacketSizes = params.retxPacketSizes;
                                          ^~~~~~~~~~~~~~~
../src/mmwave/model/mmwave-enb-mac.cc:664:43: error: ‘struct ns3::LteMacSapProvider::ReportBufferStatusParameters’ has no member named ‘retxPacketDelays’; did you mean ‘retxQueueHolDelay’?
   schedParams.m_retxPacketDelays = params.retxPacketDelays;
                                           ^~~~~~~~~~~~~~~~
../src/mmwave/model/mmwave-enb-mac.cc:665:38: error: ‘struct ns3::LteMacSapProvider::ReportBufferStatusParameters’ has no member named ‘arrivalRate’
   schedParams.m_arrivalRate = params.arrivalRate;
                                      ^~~~~~~~~~~

Waf: Leaving directory `/home/aleksandra/workspace/source/ns-3.26/build'
Build failed
 -> task in 'ns3-mmwave' failed (exit status 1): 
	{task 140643243655696: cxx mmwave-enb-mac.cc -> mmwave-enb-mac.cc.1.o}
['/usr/bin/g++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-std=c++11', '-Wno-error=deprecated-declarations', '-fstrict-aliasing', '-Wstrict-aliasing', '-fPIC', '-pthread', '-pthread', '-I.', '-I..', '-I/usr/include/gtk-2.0', '-I/usr/lib64/gtk-2.0/include', '-I/usr/include/pango-1.0', '-I/usr/include/atk-1.0', '-I/usr/include/cairo', '-I/usr/include/pixman-1', '-I/usr/include/libdrm', '-I/usr/include/gdk-pixbuf-2.0', '-I/usr/include/libpng16', '-I/usr/include/harfbuzz', '-I/usr/include/glib-2.0', '-I/usr/lib64/glib-2.0/include', '-I/usr/include/freetype2', '-I/usr/include/libxml2', '-DNS3_BUILD_PROFILE_DEBUG', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_PACKET_H=1', '-DHAVE_IF_TUN_H=1', '-DHAVE_SQLITE3=1', '-DHAVE_GTK2=1', '-DHAVE_LIBXML2=1', '../src/mmwave/model/mmwave-enb-mac.cc', '-c', '-o', '/home/aleksandra/workspace/source/ns-3.26/build/src/mmwave/model/mmwave-enb-mac.cc.1.o']
[aleksandra@localhost ns-3.26]$ 
_

Could you please help me build it successfully? I'm fairly new to ns-3 and I could really use some help.

**Comment by mychele** [comment]
Hi DmitarC,
the quickest way to use the mmWave module is to clone or download this repository.
Then you can call ./waf configure and ./waf build in the folder you downloaded.
Best,
Michele

**Comment by DmitarC** [comment]
Mychele thank You, but I have already tried this.. and it doesn't  work. 
I still get  BUILD failed, on random code line.. 
So issue isn't solved.. Do You have any other idea?

**Comment by Sourjya9015** [comment]
Can you share with us the error you are seeing on the terminal?

As Michele said, do not copy the source folder in an existing ns3 module.
Clone the entire git repository in a seperate folder and then compile.

**Comment by DmitarC** [comment]
Hi Sourjya  and mychele , I did as you said: i downloaded git repository in a new folder and tried to build it from scratch. 
Here are the outputs from ./waf configure and ./waf build commands with error at the bottom:
 
**_[aleksandra@localhost ns3-mmwave-master]$ sudo ./waf configure_**
Setting top to                           : /home/aleksandra/Documents/ns3-mmwave-master 
Setting out to                           : /home/aleksandra/Documents/ns3-mmwave-master/build 
Checking for 'gcc' (C compiler)          : /bin/gcc 
Checking for cc version                  : 6.2.1 
Checking for 'g++' (C++ compiler)        : /bin/g++ 
Checking for compilation flag -Wl,--soname=foo support : ok 
Checking for program 'python'                          : /bin/python 
Checking for python version                            : (2, 7, 12, 'final', 0) 
python-config                                          : /bin/python-config 
Asking python-config for pyembed '--cflags --libs --ldflags' flags : yes 
Getting pyembed flags from python-config                           : yes 
Asking python-config for pyext '--cflags --libs --ldflags' flags   : yes 
Getting pyext flags from python-config                             : yes 
Checking for compilation flag -fvisibility=hidden support          : ok 
Checking for compilation flag -Wno-array-bounds support            : ok 
Checking for pybindgen location                                    : ../pybindgen-0.17.0.post41+ngd10fa60 (guessed) 
Checking for python module 'pybindgen'                             : 0.17.0.post41+ngd10fa60 
Checking for pybindgen version                                     : 0.17.0.post41+ngd10fa60 
Checking for code snippet                                          : yes 
Checking for types uint64_t and unsigned long equivalence          : no 
Checking for code snippet                                          : no 
Checking for types uint64_t and unsigned long long equivalence     : yes 
Checking for the apidefs that can be used for Python bindings      : gcc-LP64 
Checking for internal GCC cxxabi                                   : complete 
Checking for python module 'pygccxml'                              : not found 
Checking boost includes                                            : 1_60 
Checking boost libs                                                : ok 
Checking for boost linkage                                         : ok 
Checking for click location                                        : not found 
Checking for program 'pkg-config'                                  : /bin/pkg-config 
Checking for 'gtk+-2.0' >= 2.12                                    : yes 
Checking for 'libxml-2.0' >= 2.7                                   : yes 
Checking for type uint128_t                                        : not found 
Checking for type __uint128_t                                      : yes 
Checking high precision implementation                             : 128-bit integer (default) 
Checking for header stdint.h                                       : yes 
Checking for header inttypes.h                                     : yes 
Checking for header sys/inttypes.h                                 : not found 
Checking for header sys/types.h                                    : yes 
Checking for header sys/stat.h                                     : yes 
Checking for header dirent.h                                       : yes 
Checking for header stdlib.h                                       : yes 
Checking for header signal.h                                       : yes 
Checking for header pthread.h                                      : yes 
Checking for header stdint.h                                       : yes 
Checking for header inttypes.h                                     : yes 
Checking for header sys/inttypes.h                                 : not found 
Checking for library rt                                            : yes 
Checking for header sys/ioctl.h                                    : yes 
Checking for header net/if.h                                       : yes 
Checking for header net/ethernet.h                                 : yes 
Checking for header linux/if_tun.h                                 : yes 
Checking for header netpacket/packet.h                             : yes 
Checking for NSC location                                          : not found 
Checking for OpenFlow location                                     : not found 
Checking for 'sqlite3'                                             : yes 
Checking for header linux/if_tun.h                                 : yes 
Checking for python module 'gtk'                                   : ok 
Checking for python module 'goocanvas'                             : 0.14.1 
Checking for python module 'pygraphviz'                            : 1.4rc1 
Checking for program 'sudo'                                        : /bin/sudo 
Checking for program 'valgrind'                                    : not found 
Checking for 'gsl'                                                 : not found 
Checking for compilation flag -Wno-error=deprecated-d... support   : ok 
Checking for compilation flag -Wno-error=deprecated-d... support   : ok 
Checking for compilation flag -fstrict-aliasing support            : ok 
Checking for compilation flag -fstrict-aliasing support            : ok 
Checking for compilation flag -Wstrict-aliasing support            : ok 
Checking for compilation flag -Wstrict-aliasing support            : ok 
Checking for program 'doxygen'                                     : /bin/doxygen 
---- Summary of optional NS-3 features:
Build profile                 : debug
Build directory               : 
Python Bindings               : enabled
Python API Scanning Support   : not enabled (Missing 'pygccxml' Python module)
BRITE Integration             : not enabled (BRITE not enabled (see option --with-brite))
NS-3 Click Integration        : not enabled (nsclick not enabled (see option --with-nsclick))
GtkConfigStore                : enabled
XmlIo                         : enabled
Threading Primitives          : enabled
Real Time Simulator           : enabled
File descriptor NetDevice     : enabled
Tap FdNetDevice               : enabled
Emulation FdNetDevice         : enabled
PlanetLab FdNetDevice         : not enabled (PlanetLab operating system not detected (see option --force-planetlab))
Network Simulation Cradle     : not enabled (NSC not found (see option --with-nsc))
MPI Support                   : not enabled (option --enable-mpi not selected)
NS-3 OpenFlow Integration     : not enabled (OpenFlow not enabled (see option --with-openflow))
SQlite stats data output      : enabled
Tap Bridge                    : enabled
PyViz visualizer              : enabled
Use sudo to set suid bit      : not enabled (option --enable-sudo not selected)
Build tests                   : not enabled (defaults to disabled)
Build examples                : not enabled (defaults to disabled)
GNU Scientific Library (GSL)  : not enabled (GSL not found)
'configure' finished successfully (3.764s)
[aleksandra@localhost ns3-mmwave-master]$ 
[aleksandra@localhost ns3-mmwave-master]$ 
[aleksandra@localhost ns3-mmwave-master]$ 
[aleksandra@localhost ns3-mmwave-master]$ 
[aleksandra@localhost ns3-mmwave-master]$ 
[aleksandra@localhost ns3-mmwave-master]$ 
**_[aleksandra@localhost ns3-mmwave-master]$ sudo ./waf build_**
Waf: Entering directory `/home/aleksandra/Documents/ns3-mmwave-master/build'
[   2/1929] Compiling install-ns3-header: ns3/antenna-model.h
[   2/1929] Compiling install-ns3-header: ns3/isotropic-antenna-model.h
[   3/1929] Compiling install-ns3-header: ns3/angles.h
[   4/1929] Compiling install-ns3-header: ns3/parabolic-antenna-model.h
[   5/1929] Compiling install-ns3-header: ns3/cosine-antenna-model.h
[   6/1929] Processing command (${PYTHON}): ../bindings/python/ns3modulegen-modular.py ../src/antenna/bindings/modulegen__gcc_LP64.py -> src/antenna/bindings/ns3module.cc src/antenna/bindings/ns3module.h src/antenna/bindings/ns3modulegen.log

[   7/1929] Compiling install-ns3-header: ns3/aodv-packet.h
[   8/1929] Compiling install-ns3-header: ns3/aodv-neighbor.h
[   9/1929] Compiling install-ns3-header: ns3/aodv-rqueue.h
[  11/1929] Compiling install-ns3-header: ns3/aodv-rtable.h
[  12/1929] Compiling install-ns3-header: ns3/aodv-id-cache.h
[  10/1929] Compiling install-ns3-header: ns3/aodv-routing-protocol.h
[  14/1929] Compiling install-ns3-header: ns3/aodv-dpd.h
[  14/1929] Compiling install-ns3-header: ns3/aodv-helper.h
[  15/1929] Processing command (${PYTHON}): ../bindings/python/ns3modulegen-modular.py ../src/aodv/bindings/modulegen__gcc_LP64.py -> src/aodv/bindings/ns3module.cc src/aodv/bindings/ns3module.h src/aodv/bindings/ns3modulegen.log

[  16/1929] Compiling install-ns3-header: ns3/udp-client.h
[  18/1929] Compiling install-ns3-header: ns3/v4ping.h
[  18/1929] Compiling install-ns3-header: ns3/packet-sink.h
[  19/1929] Compiling install-ns3-header: ns3/ping6-helper.h
[  20/1929] Compiling install-ns3-header: ns3/udp-echo-client.h
[  22/1929] Compiling install-ns3-header: ns3/ping6.h
[  23/1929] Compiling install-ns3-header: ns3/udp-echo-helper.h
[  24/1929] Compiling install-ns3-header: ns3/seq-ts-header.h
[  25/1929] Compiling install-ns3-header: ns3/on-off-helper.h
[  26/1929] Compiling install-ns3-header: ns3/radvd-helper.h
[  27/1929] Compiling install-ns3-header: ns3/v4ping-helper.h
[  21/1929] Compiling install-ns3-header: ns3/radvd-prefix.h
[  28/1929] Compiling install-ns3-header: ns3/packet-loss-counter.h
[  29/1929] Compiling install-ns3-header: ns3/udp-trace-client.h
[  30/1929] Compiling install-ns3-header: ns3/packet-sink-helper.h
[  31/1929] Compiling install-ns3-header: ns3/udp-echo-server.h
[  32/1929] Compiling install-ns3-header: ns3/application-packet-probe.h
[  33/1929] Compiling install-ns3-header: ns3/bulk-send-application.h
[  34/1929] Compiling install-ns3-header: ns3/udp-client-server-helper.h
[  35/1929] Compiling install-ns3-header: ns3/radvd.h
[  36/1929] Compiling install-ns3-header: ns3/bulk-send-helper.h

...
[1451/1929] Compiling src/lr-wpan/model/lr-wpan-spectrum-signal-parameters.cc
[1452/1929] Compiling src/internet/helper/ipv4-routing-helper.cc
[1453/1929] Compiling src/dsr/model/dsr-gratuitous-reply-table.cc
[1454/1929] Compiling src/applications/helper/udp-client-server-helper.cc
[1455/1929] Compiling src/antenna/model/isotropic-antenna-model.cc
[1456/1929] Compiling src/antenna/model/angles.cc
[1457/1929] Compiling src/config-store/model/model-node-creator.cc
[1458/1929] Compiling src/internet/model/ipv6-extension-demux.cc
[1459/1929] Compiling src/internet/model/tcp-socket.cc
[1460/1929] Compiling src/internet/model/ipv4.cc
[1461/1929] Compiling src/lte/model/lte-enb-rrc.cc
[1462/1929] Compiling src/lte/model/lte-ue-rrc.cc
[1463/1929] Compiling src/lte/helper/phy-tx-stats-calculator.cc
[1464/1929] Compiling src/netanim/model/animation-interface.cc
[1465/1929] Compiling src/spectrum/model/waveform-generator.cc
[1466/1929] Compiling build/src/wave/bindings/ns3module.cc
[1467/1929] Compiling src/wifi/model/dsss-error-rate-model.cc
[1468/1929] Compiling src/wifi/model/originator-block-ack-agreement.cc
[1469/1929] Compiling src/wifi/helper/wifi-radio-energy-model-helper.cc
[1470/1929] Compiling build/src/wimax/bindings/ns3module.cc
[1471/1929] Compiling src/wimax/model/mac-messages.cc
[1472/1929] Compiling src/wifi/model/msdu-standard-aggregator.cc
[1473/1929] Compiling src/wifi/model/sta-wifi-mac.cc
[1474/1929] Compiling src/wifi/model/ssid.cc
[1475/1929] Compiling src/wave/model/vendor-specific-action.cc
[1476/1929] Compiling src/topology-read/model/topology-reader.cc
[1477/1929] Compiling src/stats/model/omnet-data-output.cc
[1478/1929] Compiling src/spectrum/model/wifi-spectrum-value-helper.cc
[1479/1929] Compiling src/network/utils/address-utils.cc
[1480/1929] Compiling src/mobility/model/constant-acceleration-mobility-model.cc
[1481/1929] Compiling src/mobility/model/box.cc
[1482/1929] Compiling src/lte/model/ff-mac-common.cc
[1483/1929] Compiling src/internet/model/tcp-option-winscale.cc
[1484/1929] Compiling src/internet/model/arp-l3-protocol.cc
[1485/1929] Compiling src/flow-monitor/model/flow-probe.cc
[1486/1929] Compiling src/core/model/unix-system-condition.cc
[1487/1929] Compiling src/core/model/event-id.cc
[1488/1929] Compiling src/core/model/list-scheduler.cc
[1489/1929] Compiling src/core/model/heap-scheduler.cc
[1490/1929] Compiling src/core/model/calendar-scheduler.cc
[1491/1929] Compiling src/flow-monitor/model/flow-classifier.cc
[1492/1929] Compiling src/internet/model/ip-l4-protocol.cc
[1493/1929] Compiling src/internet/model/tcp-option-ts.cc
[1494/1929] Compiling src/lte/model/lte-anr.cc
[1495/1929] Compiling src/mesh/model/mesh-l2-routing-protocol.cc
[1496/1929] Compiling src/mesh/model/mesh-wifi-interface-mac.cc
[1497/1929] Compiling src/mmwave/model/mmwave-phy-sap.cc
[1498/1929] Compiling build/src/sixlowpan/bindings/ns3module.cc
[1499/1929] Compiling src/spectrum/model/spectrum-model.cc
[1500/1929] Compiling src/spectrum/model/spectrum-phy.cc
[1501/1929] Compiling src/wifi/helper/ht-wifi-mac-helper.cc
[1502/1929] Compiling src/wifi/model/interference-helper.cc
[1503/1929] Compiling src/uan/model/uan-transducer.cc
[1504/1929] Compiling src/network/utils/output-stream-wrapper.cc
[1505/1929] Compiling build/src/mesh/bindings/ns3module.cc
[1506/1929] Compiling src/energy/model/simple-device-energy-model.cc
[1507/1929] Compiling src/energy/model/basic-energy-source.cc
[1508/1929] Compiling src/dsr/model/dsr-rcache.cc
[1509/1929] Compiling src/csma/helper/csma-helper.cc
[1510/1929] Compiling src/aodv/model/aodv-rqueue.cc
[1511/1929] Compiling src/dsr/model/dsr-passive-buff.cc
[1512/1929] Compiling src/internet/model/ipv6-extension.cc
[1513/1929] Compiling src/internet/model/ipv6-routing-table-entry.cc
[1514/1929] Compiling src/lte/model/lte-pdcp.cc
[1515/1929] Compiling src/lte/model/epc-sgw-pgw-application.cc
[1516/1929] Compiling src/mesh/model/dot11s/hwmp-tag.cc
[1517/1929] Compiling src/olsr/model/olsr-header.cc
[1518/1929] Compiling src/stats/model/boolean-probe.cc
[1519/1929] Compiling src/wimax/model/service-flow.cc
[1520/1929] Compiling src/wimax/model/simple-ofdm-wimax-phy.cc
[1521/1929] Compiling build/src/tap-bridge/bindings/ns3module.cc
[1522/1929] Compiling build/src/stats/bindings/ns3module.cc
[1523/1929] Compiling src/spectrum/model/single-model-spectrum-channel.cc
[1524/1929] Compiling src/propagation/model/itu-r-1411-los-propagation-loss-model.cc
[1525/1929] Compiling src/network/utils/llc-snap-header.cc
[1526/1929] Compiling src/mmwave/model/mmwave-beamforming.cc
[1527/1929] Compiling src/lte/helper/lte-hex-grid-enb-topology-helper.cc
[1528/1929] Compiling src/lte/model/lte-rlc-am.cc
[1529/1929] Compiling src/lte/model/lte-common.cc
../src/lte/model/lte-rlc-am.cc:431:51: error: stray ‘\342’ in program
          if(bytes<firstSegHdr.GetSerializedSize ()​)​
                                                   ^
../src/lte/model/lte-rlc-am.cc:431:52: error: stray ‘\200’ in program
          if(bytes<firstSegHdr.GetSerializedSize ()​)​
                                                    ^
../src/lte/model/lte-rlc-am.cc:431:53: error: stray ‘\213’ in program
          if(bytes<firstSegHdr.GetSerializedSize ()​)​
                                                     ^
../src/lte/model/lte-rlc-am.cc:431:55: error: stray ‘\342’ in program
          if(bytes<firstSegHdr.GetSerializedSize ()​)​
                                                       ^
../src/lte/model/lte-rlc-am.cc:431:56: error: stray ‘\200’ in program
          if(bytes<firstSegHdr.GetSerializedSize ()​)​
                                                        ^
../src/lte/model/lte-rlc-am.cc:431:57: error: stray ‘\213’ in program
          if(bytes<firstSegHdr.GetSerializedSize ()​)​
                                                         ^

**Waf: Leaving directory `/home/aleksandra/Documents/ns3-mmwave-master/build'
Build failed
 -> task in 'ns3-lte' failed (exit status 1): 
	{task 140163733747088: cxx lte-rlc-am.cc -> lte-rlc-am.cc.1.o}
['/bin/g++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-Wno-error=deprecated-declarations', '-fstrict-aliasing', '-Wstrict-aliasing', '-fPIC', '-pthread', '-pthread', '-I.', '-I..', '-I/usr/include/gtk-2.0', '-I/usr/lib64/gtk-2.0/include', '-I/usr/include/pango-1.0', '-I/usr/include/atk-1.0', '-I/usr/include/cairo', '-I/usr/include/pixman-1', '-I/usr/include/libdrm', '-I/usr/include/gdk-pixbuf-2.0', '-I/usr/include/libpng16', '-I/usr/include/harfbuzz', '-I/usr/include/glib-2.0', '-I/usr/lib64/glib-2.0/include', '-I/usr/include/freetype2', '-I/usr/include/libxml2', '-DNS3_BUILD_PROFILE_DEBUG', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_PACKET_H=1', '-DHAVE_IF_TUN_H=1', '-DHAVE_SQLITE3=1', '-DHAVE_GTK2=1', '-DHAVE_LIBXML2=1', '../src/lte/model/lte-rlc-am.cc', '-c', '-o', '/home/aleksandra/Documents/ns3-mmwave-master/build/src/lte/model/lte-rlc-am.cc.1.o']**

**Comment by Sourjya9015** [comment]
Michele,

I received a similar error last time I downloaded the repo (last Monday I
guess). These seems to be some unwanted escape sequences present. Can you
take a look at these. I will suggest opening the affected files using vim
or nano editors from your terminal and removing the specific escape
sequences. They will not appear if you use Eclipse or some more
sophisticated editors.

Let me know.

--Sourjya.

Sourjya Dutta,
ECE Department,
NYU Tandon School of Engineering.

**Comment by DmitarC** [comment]
Just to make it clear: building fails every time at different code line.

**Comment by Sourjya9015** [comment]
DmitarC,

It is on the same rlc-am file, right? That is the file I was getting the
error on.

--Sourjya.

Sourjya Dutta,
ECE Department,
NYU Tandon School of Engineering.

**Comment by DmitarC** [comment]
No. I just tried once more and I got this error:

[1412/1929] Compiling src/wimax/model/wimax-net-device.cc
[1413/1929] Compiling src/wifi/helper/athstats-helper.cc
[1414/1929] Compiling src/wifi/model/aparf-wifi-manager.cc
In file included from ../src/wifi/helper/athstats-helper.cc:23:0:
../src/wifi/helper/athstats-helper.cc: In member function ‘void ns3::AthstatsWifiTraceSink::WriteStats()’:
./ns3/abort.h:110:5: error: nonnull argument ‘this’ compared to NULL [-Werror=nonnull-compare]
     if (cond)                                                          \
     ^
./ns3/abort.h:145:3: note: in expansion of macro ‘NS_ABORT_MSG_IF’
   NS_ABORT_MSG_IF (!(cond),msg)
   ^~~~~~~~~~~~~~~
../src/wifi/helper/athstats-helper.cc:262:3: note: in expansion of macro ‘NS_ABORT_MSG_UNLESS’
   NS_ABORT_MSG_UNLESS (this, "function called with null this pointer, now=" << Now () );
   ^~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

Waf: Leaving directory `/home/aleksandra/Documents/ns3-mmwave-master/build'
Build failed
 -> task in 'ns3-wifi' failed (exit status 1): 
	{task 139629326858512: cxx athstats-helper.cc -> athstats-helper.cc.1.o}
['/bin/g++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-Wno-error=deprecated-declarations', '-fstrict-aliasing', '-Wstrict-aliasing', '-fPIC', '-pthread', '-pthread', '-I.', '-I..', '-I/usr/include/gtk-2.0', '-I/usr/lib64/gtk-2.0/include', '-I/usr/include/pango-1.0', '-I/usr/include/atk-1.0', '-I/usr/include/cairo', '-I/usr/include/pixman-1', '-I/usr/include/libdrm', '-I/usr/include/gdk-pixbuf-2.0', '-I/usr/include/libpng16', '-I/usr/include/harfbuzz', '-I/usr/include/glib-2.0', '-I/usr/lib64/glib-2.0/include', '-I/usr/include/freetype2', '-I/usr/include/libxml2', '-DNS3_BUILD_PROFILE_DEBUG', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_PACKET_H=1', '-DHAVE_IF_TUN_H=1', '-DHAVE_SQLITE3=1', '-DHAVE_GTK2=1', '-DHAVE_LIBXML2=1', '../src/wifi/helper/athstats-helper.cc', '-c', '-o', '/home/aleksandra/Documents/ns3-mmwave-master/build/src/wifi/helper/athstats-helper.cc.1.o']
[aleksandra@localhost ns3-mmwave-master]$

**Comment by zml312570140** [comment]
Hi guys,

One of the bugs is from my previous commit. I already fixed that in the new
commit.

*DmitarC*, you first sync with the latest ns3 git repository and run the
following scripts to build,

CXXFLAGS='-Wall' ./waf configure enable-examples
./waf build

Let me know if you still have any issue.

Menglei

**Comment by DmitarC** [comment]
Hi, 
now it is working correctly, after sync and with 
CXXFLAGS='-Wall' ./waf configure --enable-examples
 ./waf build
Thank You all.

**Comment by DmitarC** [comment]
Sorry for reopening this topic, but I have just one more question: is there any documentation explaining the scenarios? I only found these two papers:
https://arxiv.org/pdf/1506.08801v1.pdf
https://arxiv.org/pdf/1602.06932.pdf

but only the latter has two scripts from module explained. Is there some overall description of module?
Thank you!
